### ISSUE TITLE
Connectivity requirement clarification

### ISSUE THREAD

**Issue by netapp-bingen** [NetAppDocs/cloud-manager-backup-restore#104]
Page: [Register SnapCenter Plug-in for VMware vSphere host](https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-register-snapCenter-plug-in-for-vmware-vsphere.html)

When you say communication between BlueXP and SCV, do you mean the website or the on-prem acquisition unit?

**Comment by netapp-manishc** [comment]
@netapp-bingen: This means the communication should be open between the on-prem SCV which is running on default 8144 port and the BlueXP Connector instance which could be either running in any cloud providers (Azure, GCP, AWS) or on-prem.

**Comment by netapp-bingen** [comment]
> @netapp-bingen: This means the communication should be open between the on-prem SCV which is running on default 8144 port and the BlueXP Connector instance which could be either running in any cloud providers (Azure, GCP, AWS) or on-prem.

Ok, that's great information. Do you think it might be possible to add that to the doc?

**Comment by netapp-manishc** [comment]
@netapp-bingen: I have included this information to the topic: https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-register-snapCenter-plug-in-for-vmware-vsphere.html

**Comment by netapp-bingen** [comment]
Looks great, thanks for the rapid turnaround!
