### ISSUE TITLE
Suggest for Japanese translation.

### ISSUE THREAD

**Issue by imasafum** [NetAppDocs/cloud-manager-backup-restore#11]
Page: [オンプレミスの ONTAP データの Amazon S3 へのバックアップ](https://docs.netapp.com/ja-jp/occm/task_backup_onprem_to_aws.html)

To whom it may concern.
I'd like to suggest translation modification.

クラスタには SnapMirror ライセンスがあります。
↓
クラスタにはSnapMirror ライセンスが必要です。

Could you please consider.

Best regards,

**Comment by ntap-bmegan** [comment]
@netapp-gudugunti?

**Comment by ntap-bmegan** [comment]
This issue will be closed on tues 30 aug 2022 due to lack of activity within the last 30 days. @imasafum - If you believe that the original problem persists, please comment in this issue to keep it open for further review.

**Comment by ntap-bmegan** [comment]
This issue has been closed due to inactivity. Any interested party can comment to reopen the issue.
