### ISSUE TITLE
CMEK Considerations - KMS API

### ISSUE THREAD

**Issue by trevorjth** [NetAppDocs/cloud-manager-backup-restore#115]
Page: [Backing up on-premises ONTAP data to Google Cloud Storage](https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-onprem-to-gcp.html)

I believe we need to add to the considerations section that we need the KMS API enabled on the project of the bxp connector

**Comment by netapp-tonacki** [comment]
Hi Trevor.  Thanks for your comment.  I need a little more information.  
Why do you think this is needed?  Did something not work correctly because the API wasn't enabled?
Is enabling the KMS API needed in general, or only if the user plans to use CMEK?

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi Trevor.  Thanks for your email to clarify this issue. I replied back on the 28th, so please let me know if we're all set with this issue.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi,  Trevor and I have had other email discussions about this item.  I have made some updates in the [Connector docs](https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-enable-apis-google.html) to mention this needed API when enabling other Google APIs.

I am updating the Backups docs for on-prem ONTAP backup to GCP and CVO backup to GCP.  I will publish these changes shortly.  Then I'll close this issue.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
I have added that the user needs to verify that they have the correct API enabled before attempting to use CMEKs.  It is the on-prem ONTAP backup to GCP and CVO backup to GCP topics in the section on CMEK.
