### ISSUE TITLE
Add section on Cloud Backup when it's consumed via a CVO Professional license

### ISSUE THREAD

**Issue by phoebegoh** [NetAppDocs/cloud-manager-backup-restore#12]
Page: [Learn about Cloud Backup](https://docs.netapp.com/us-en/occm/concept_backup_to_cloud.html)

I feel like it isn't clear in the Licensing section of Cloud Backup how this works when the CVO environment is licensed using the Professional package (which includes unlimited backups, see https://docs.netapp.com/us-en/occm/concept_licensing.html#licensing-overview)

**Comment by netapp-tonacki** [comment]
Hi Phoebe,  Sorry for the delay...  But I finally made changes to the [Cloud Backup Licensing topic](https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-licensing-cloud-backup.html#use-a-cloud-backup-paygo-subscription) and the [Cloud Backup for ONTAP Overview topic](https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-ontap-backup-to-cloud.html#annual-contract-aws-only) to clarify how the Professional license works.  Let me know if you think it can be clarified further.

Thanks, Tom
