### ISSUE TITLE
[Question] BYOL license

### ISSUE THREAD

**Issue by YasutakaNN** [NetAppDocs/cloud-manager-backup-restore#17]
Page: [Set up licensing for Cloud Backup](https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-licensing-cloud-backup.html)

Hi team,

Let me ask a question about BYOL license.

When backups have reached more than 100% of licensed capacity, what will happen the next ? 

If the account you are using has a marketplace account, the backup service continues to run, but you are shifted over to a PAYGO licensing model. 
If the account you are does not have a marketplace account, does the backup service stop ?

**Comment by netapp-tonacki** [comment]
Hi Yasutaka,  In the docs we say that backup continues and that users will be charged for all of that backup activity once they renew the license.  But I am going to double-check.  I'll let you know 

Thanks for bringing this up.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi Yasutaka,  I have verified that backup is not stopped if the BYOL license expires and there's no subscribed PAYGO license.  The user will receive license warnings until they update the BYOL license.  

Some small changes in how licensing is implemented starting today with the May software update.  See the [Release Notes](https://docs.netapp.com/us-en/cloud-manager-backup-restore/whats-new.html#2-may-2022) and the [Licensing topic](https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-licensing-cloud-backup.html) for more info.

Thanks, Tom

**Comment by YasutakaNN** [comment]
Hi Tom-san,

Thank you very much for your reply. I solved my question clearly.
I will definitely check both release notes and licensing topic soon.

Yasu

**Comment by YasutakaNN** [comment]
Hi Tom-san,

I would like to ask just in case.
Regarding my question "When **backups have reached more than 100%** of licensed capacity, what will happen the next ?",  the backup is not stopped if the BYOL license **reaches more than 100%** and there's no subscribed PAYGO license as well. Is that correct ? 

Yasu

**Comment by netapp-tonacki** [comment]
Yes, that is the response I got from the team.

Tom

**Comment by YasutakaNN** [comment]
Thank you very much, Tom-san!

Yasu

**Comment by netapp-tonacki** [comment]
You're welcome Yasu.   Thanks for bringing up this question so I could clarify the docs,

Thanks, Tom
