### ISSUE TITLE
"Supported functionalities" is awkwardly phrased

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/cloud-manager-backup-restore#36]
Page: [Protect your cloud native applications data](https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-protect-cloud-app-data-to-cloud.html)

I don't believe a "Supported functionalities" heading is a standard in other IE docs. It's also not a typical phrase. "Functionality" is a very engineering'ese word to use in end-user documentation, and its plural form in end-user docs is even odder. Can we do better here?

**Comment by netapp-soumikd** [comment]
Thank you Adam for your feedback. 

Discussed with Tom and changed the title to: "Features".
The updated content is published: https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-protect-cloud-app-data-to-cloud.html#features
