### ISSUE TITLE
Add CBS license mix&match mechanism to improve overall understanding

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/cloud-manager-backup-restore#44]
Page: [Set up licensing for Cloud Backup](https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-licensing-cloud-backup.html)

Hi Team, currently we need to read this whole page to understand PAYG and BYOL licenses are used by Digital Wallet in the best way to do a mix&match to charge for protected data. Cloud Manager refers to Digital Wallet available subscriptions and BYOL licenses to cover the costs giving priority to BYOL licenses and covering the gaps with PAYG payments in my understanding.

Could we confirm the mechanism with the team and add one point at "A few notes before you read any further:" roughly explaining the mechanism?

Example:
- Customers can have PAYG subscriptions and CBS BYOL licenses in the Digital Wallet. Cloud Manager will refer to the Digital Wallet to apply the appropriate mix of available licenses. As an example if a customer is protecting 100TiB with a PAYG marketplace subscription and adds 60TiB BYOL, Cloud Manager will cover the extra 40TiB with the PAYG subscription. When the BYOL will expire, Cloud Manager will continue charging 100TiB from Marketplace PAYG.

Regards,
Gabriel

**Comment by netapp-tonacki** [comment]
Thanks for the comment Gabriel.  I'll double-check with the team and work on adding something that describes how the 2 license types interoperate.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi Gabriel,  I added a new bullet number 3 at the top of the [Set up licensing for Cloud Backup](https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-licensing-cloud-backup.html) topic to explain this.  I did not include an example of TiBs used, etc. because the section that follows right below about PAYGO has a description already.

Let me know what you think.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi Gabriel,  Thanks for your thoughts about this content. Adding a PAYGO on top of a BYOL has the advantage of no down time if the user goes over their BYOL capacity. What is the advantage of adding a BYOL on top of a PAYGO?  If there is one, I would figure out a way to add your suggestion.  But right now I don't see the incentive for the user.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi Gabriel,  If there is an advantage of adding a BYOL on top of a PAYGO, let me know.  Otherwise I'll close this item for now.

Thanks, Tom

**Comment by gabrieltokyo** [comment]
Sorry for late reply, not sure we can directly write it but normally is due to better economics.

A customer may start with a subscription, when they stabilize... may be willing to commit for a certain quantity they know they need to cover at better price committing 1 or more years at a better price than marketplace price.

Thanks, Gabriel

**Comment by netapp-tonacki** [comment]
OK, I understand now.  I'll check with PM to see if this is a message they want added to the docs.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi Gabriel,  PM explained to me that users who sign up for 1-, 2-, 3-year Contract thru the Marketplace, or with Private offer, can get pricing like BYOL, so BYOL is not always a savings.  So I think I'm going to leave the docs as they are.

Thanks, Tom

**Comment by gabrieltokyo** [comment]
Yes, that's exactly the concern I was having.
It's just many sellers tend to think more in BYOL and do questions that could be solved reading the document.

I understand the decision and we can close the thread.
It improved the understanding with the changes and many guys will connect the dots.

**Comment by netapp-tonacki** [comment]
Thanks for all your feedback about this content Gabriel.

Thanks, Tom
