### ISSUE TITLE
404 on some links from this page

### ISSUE THREAD

**Issue by dclaybrook** [NetAppDocs/cloud-manager-backup-restore#52]
Page: [Cloud Backup documentation](https://docs.netapp.com/us-en/cloud-manager-backup-restore/index.html)

The link to [Back up on-premises applications data to cloud](https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-app-data-to-cloud.html) lands on a 404.
I also noticed that [Back up datastores to cloud](https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-vm-data-to-cloud.html) is a 404 as well.

**Comment by netapp-soumikd** [comment]
Thanks for your query. We will verify and get back at the earliest.

Thanks,
Soumik

**Comment by netapp-soumikd** [comment]
The links have been fixed. You can verify here: https://docs.netapp.com/us-en/cloud-manager-backup-restore/index.html
