### ISSUE TITLE
generate fr and de - 2813

### ISSUE THREAD

**Issue by netapp-gudugunti** [NetAppDocs/cloud-manager-backup-restore#61]
A localization admin will generate the French and German sites. 

### Site maintainers and mergers
Comment in this issue if you update the English site before the issue closes. No other action is required on your part.

**Comment by netapp-tonacki** [comment]
Hi, I made some updates just now: https://github.com/NetAppDocs/cloud-manager-backup-restore/pull/62

Tom

**Comment by dmajones** [comment]
Sites (fr & de) are up and running. BPR set.
Total TOT 7 minutes.
