### ISSUE TITLE
Is the formatting correct in the "Preparing StorageGRID" section?

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/cloud-manager-backup-restore#64]
Page: [Backing up on-premises ONTAP data to StorageGRID](https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-onprem-private-cloud.html)

Inside the "Preparing StorageGRID" section, we describe requirements and it seems like we might have intended to present the information in a bulleted list but it isn't rendered as such.

These are the lines in question:

> StorageGRID must meet the following requirements. See the [StorageGRID documentation](https://docs.netapp.com/us-en/storagegrid-116/) for more information.
> 
> Supported StorageGRID versions
> StorageGRID 10.3 and later is supported.
> 
> To use DataLock & Ransomware Protection for your backups, your StorageGRID systems must be running version 11.6.0.3 or greater.
> 
> S3 credentials
> You must have created an S3 tenant account to control access to your StorageGRID storage. [See the StorageGRID docs for details](https://docs.netapp.com/us-en/storagegrid-116/admin/creating-tenant-account.html).

**Comment by netapp-tonacki** [comment]
Hey adamn-ntap,  ;-) Thanks for your comment.  This issue came up recently and is reported in https://github.com/NetAppDocs/docs-help/discussions/892 . The formatting issue is across repos and should be fixed soon.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
This CSS issue was fixed and I have rebuilt the repo.   Thanks, Tom
