### ISSUE TITLE
Clarification on VPC endpoint

### ISSUE THREAD

**Issue by laagabi** [NetAppDocs/cloud-manager-backup-restore#65]
Page: [Backing up Cloud Volumes ONTAP data to Amazon S3](https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-to-s3.html)

Hello Team,

Looking for clarification on what type of VPC endpoint we referring to on this diagram? 
![image](https://user-images.githubusercontent.com/80273701/204008044-e4edad7f-04be-4309-b84e-1e6fbaf43530.png)

Based on the CVO docs, we speculate that this might be a gateway vpc endpoint. Is it possible to get a hyperlink to any configuration workflow?

**Comment by netapp-tonacki** [comment]
Hi Gabor,  Thanks for your comment.  It does need to be clarified whether this is a "gateway endpoint" or an "interface endpoint". I am pretty sure it is an "interface endpoint", but I will double-check and get back too you.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi again Gabor.  I got an answer and it is a "gateway endpoint" that you want - like you had thought.  A link to Amazon docs is here (https://docs.aws.amazon.com/vpc/latest/privatelink/vpc-endpoints-s3.html).  Is this what you were looking for?

I will update the Backup docs to make this distinction.

Thanks, Tom

**Comment by laagabi** [comment]
Thanks Tom,

Are there specific requirements for CBS, so any specific permissions or anything that we must consider setting up the vpc gateway endpoint?

BR,
Gabor.

**Comment by netapp-tonacki** [comment]
Hi Gabor,  No, nothing specific for Cloud Backup config that have heard about.

**Comment by laagabi** [comment]
Thanks Tom,

Could you please update the docs and put the bit about the vpc endpoint type and maybe the link to the aws docs?

After that, I think we are ok to close this issue.

BR,
Gabor.

**Comment by netapp-tonacki** [comment]
Yup, I'll do that Gabor.  Thanks again for your comment.  Should be updated in a couple days.

Tom

**Comment by netapp-tonacki** [comment]
Hi Gabor, I updated the diagram, and then after that I provided a link to AWS docs for info about gateway endpoints.

Thanks, Tom
