### ISSUE TITLE
Broken Link: Delete Your Backups

### ISSUE THREAD

**Issue by nickfritsch** [NetAppDocs/cloud-manager-backup-restore#66]
Page: [Managing backups for your ONTAP systems](https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-manage-backups-ontap.html)

On this page, under the heading: Enabling and disabling backups of volumes; the hyperlink to "delete your backups" in the second paragraph of this section is broken. It returns a 404 error. Thank you.

**Comment by netapp-tonacki** [comment]
Hi Nick,  Thanks for catching this.  I am working on changes to this content currently and will post a fixed version in the next day or 2.

Thanks again, Tom

**Comment by netapp-tonacki** [comment]
This change is now live.  https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-manage-backups-ontap.html#enabling-and-disabling-backups-of-volumes

Thanks again Nick
