### ISSUE TITLE
Permission list does not contain all required items

### ISSUE THREAD

**Issue by kholger** [NetAppDocs/cloud-manager-backup-restore#71]
Page: [Backing up Cloud Volumes ONTAP data to Azure Blob storage](https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-to-azure.html)

Should be synced with this
https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-permissions-azure.html#cloud-backup

Cloud Backup
The Connector makes the following API requests for backup and restore operations:

Microsoft.Compute/virtualMachines/read

Microsoft.Compute/virtualMachines/start/action

Microsoft.Compute/virtualMachines/deallocate/action

Microsoft.Storage/storageAccounts/listkeys/action

Microsoft.Storage/storageAccounts/read

Microsoft.Storage/storageAccounts/write

Microsoft.Storage/storageAccounts/blobServices/containers/read

Microsoft.KeyVault/vaults/read

Microsoft.KeyVault/vaults/accessPolicies/write

Microsoft.Network/networkInterfaces/read

Microsoft.Resources/subscriptions/locations/read

Microsoft.Network/virtualNetworks/read

Microsoft.Network/virtualNetworks/subnets/read

Microsoft.Resources/subscriptions/resourceGroups/read

Microsoft.Resources/subscriptions/resourcegroups/resources/read

Microsoft.Resources/subscriptions/resourceGroups/write

Microsoft.Authorization/locks/*

Microsoft.Network/privateEndpoints/write

Microsoft.Network/privateEndpoints/read

Microsoft.Network/privateDnsZones/virtualNetworkLinks/write

Microsoft.Network/virtualNetworks/join/action

Microsoft.Network/privateDnsZones/A/write

Microsoft.Network/privateDnsZones/read

Microsoft.Network/privateDnsZones/virtualNetworkLinks/read

Microsoft.Compute/virtualMachines/extensions/delete

Microsoft.Compute/virtualMachines/delete

Microsoft.Network/networkInterfaces/delete

Microsoft.Network/networkSecurityGroups/delete

Microsoft.Resources/deployments/delete

Microsoft.Network/publicIPAddresses/delete

Microsoft.Storage/storageAccounts/blobServices/containers/write

Microsoft.ManagedIdentity/userAssignedIdentities/assign/action

Thx
Holger

**Comment by netapp-tonacki** [comment]
Hi Holger,  Thanks for your comment.  I will sync the permissions in the Backup topic with what's in the Connector topic.  I'll let you know when it is done.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi Holger, Sorry for the delay on this request.  I have updated the page with the full list of permissions now.  Thanks again for your feedback.

Tom
