### ISSUE TITLE
Alignment issue with table

### ISSUE THREAD

**Issue by sabarig84** [NetAppDocs/cloud-manager-backup-restore#72]
Page: [Restoring ONTAP data from backup files](https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-restore-backups-ontap.html)

On the below link there seems to be alignment issue, which makes it very confusing. Please fix it.
https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-restore-backups-ontap.html#browse-restore-supported-working-environments-and-object-storage-providers

**Comment by sabarig84** [comment]
<img width="864" alt="Cloudbackup table" src="https://user-images.githubusercontent.com/45964094/207327613-2e247039-0483-46bc-84ef-24c4fc50f895.png">

**Comment by netapp-tonacki** [comment]
Hi Sabari,  Thanks for catching this.  I noticed this yesterday and I have a fix ready to go live as soon as I get the go ahead.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
This table issue is fixed. Thanks for reporting it.   Tom
