### ISSUE TITLE
Feedback on  'Viewing the list of backups for each volume'

### ISSUE THREAD

**Issue by netapp-chandaj** [NetAppDocs/cloud-manager-backup-restore#82]
Page: [Managing backups for your ONTAP systems](https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-manage-backups-ontap.html)

On this Page in the section https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-manage-backups-ontap.html#viewing-the-list-of-backups-for-each-volume

**Viewing the list of backups for each volume**
You can view the list of all backup files that exist for each volume. This page displays details about the source volume, destination location, and backup details such as last backup taken, the current backup policy, backup file size, and more.
This page also enables you perform the following tasks:
•	Delete all backup files for the volume
•	Delete individual backup files for the volume
•	Download a backup report for the volume     **<<< there is no such option on the backup list page, can you elaborate or correct this**
Steps
1.	From the Volumes tab, click   for the source volume and select Details & Backup List.
 
![image](https://user-images.githubusercontent.com/66023260/215117931-47a117aa-546f-4e98-a72e-4b6e2abede9f.png)

The list of all backup files is displayed along with details about the source volume, destination location, and backup details.
 
![image](https://user-images.githubusercontent.com/66023260/215117985-63b94f8a-8961-4a73-870b-b1f8de4748c0.png)

**Comment by netapp-tonacki** [comment]
Thanks Chanda.  I'll take a look at this to see what happened.  I think the report option was delayed and I left this text by mistake.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi Chanda,  I removed that bullet from the topic.  Thanks again for letting me know.

Thanks, Tom
