### ISSUE TITLE
Index-style Japanese used in body text in ja-jp version 

### ISSUE THREAD

**Issue by yukakou** [NetAppDocs/cloud-manager-backup-restore#84]
Page: [クラウドへのバックアップの詳細をご確認ください](https://docs.netapp.com/ja-jp/occm38/concept_backup_to_cloud.html)

Hi @netapp-gudugunti ,
I'm opening this ticket for the issue that was reported by https://github.com/NetAppDocs/occm.ja-jp/issues/1 and still exists.
https://docs.netapp.com/ja-jp/cloud-manager-backup-restore/concept-backup-to-cloud.html#cloud-backup-%E3%81%AE%E4%BB%95%E7%B5%84%E3%81%BF

English: Where backups reside
Current Translation: バックアップの保管場所バックアップノバショ
Expected Translation: バックアップの保管場所

Katakana word is added after the exact translation which seems like an index style in Japanese. It might be worth investigating if It might come from an unintentionally-registered segment in TM. Otherwise, I'm afraid something may wrong with the NMT engine.

![ja_jp](https://user-images.githubusercontent.com/50446078/215913191-eef7c68c-a031-4da2-a183-d69750113f0a.gif)

Thanks for your support!
Yuka

**Comment by netapp-gudugunti** [comment]
Thanks! @yukakou and @netapp-bcammett.
We shall investigate and get back on this.

**Comment by netapp-gudugunti** [comment]
@yukakou and @netapp-bcammett, 
The issue is fixed.
Thanks! for bringing this to our attention.

**Comment by yukakou** [comment]
I confirmed the fix, thank you, @netapp-gudugunti !
