### ISSUE TITLE
Job Monitor is showing only manually initiated Tasks

### ISSUE THREAD

**Issue by astralinhalator** [NetAppDocs/cloud-manager-backup-restore#85]
Currently the Jobmonitoring is showing only manually initiated task... this behavior we have in our environment since 04/2022.... i cannot find this  information in the docs... more or  less it looks that some  parts of the job monitoring are maybe currently not released.  In our Environment Job Monitoring is useable only for manually initiated backups via cloudbackup or for restore   or also some manually initiated search job are dispayed... but not the automatically backups which are organized via e.g. netapp3monthsretention

**Comment by netapp-tonacki** [comment]
Hi astra,  Thanks for your comment.  On the page https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-monitor-backup-jobs.html there is text that says "Note that system-initiated jobs, such ongoing backup operations, are not reflected in the Job Monitoring tab — only user-initiated jobs are displayed.".  Does this cover what you are seeing?

Thanks, Tom

**Comment by astralinhalator** [comment]
well it's a small sentence which could be overlooked in combination whith a little bit  misleading screenshot because this jobs looks not really user-initiated. and it is not only the small sentence... also support don't know it last year and thought that every backup is displayed there.

**Comment by netapp-tonacki** [comment]
Hi astra,  I can make that sentence into a Note that will have an icon and draw more attention to it.  I know that showing automated jobs is being worked on, but I don't know when it may be available.

Thanks, Tom

**Comment by astralinhalator** [comment]
yes that sounds a good idea

**Comment by netapp-tonacki** [comment]
I'll make that change.  I have some doc revisions coming out next week, so I'll add this change with that update.  Thanks for your feedback astral
