### ISSUE TITLE
Add requirement that only NFS datastores are supported

### ISSUE THREAD

**Issue by si-heger** [NetAppDocs/cloud-manager-backup-restore#88]
Page: [Protect your virtual machines data](https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-protect-vm-data.html)

Only NFS datastore are supported. Customers with VMFS datastores based on iSCSI/FC/NVMe or vVOls cannot use this.

**Comment by netapp-manishc** [comment]
I have updated the following topic to mention that VMFS datastores and vVOls are not supported:

https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-manage-vm-data-in-cloud.html#view-the-datastores-and-virtual-machines

**Comment by si-heger** [comment]
Hi Manish, it would be awesome if you could add the requirement to have NFS datastores in the requirements page as I posted above. It is really complicated to post requirements over multiple different pages if we have one dedicated first page in the documentation that lists explicit requirements.

So please again: Add the requirement to have NFS datastores and not VMFS in the requirements page here: https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-protect-vm-data.html

**Comment by netapp-manishc** [comment]
Hi Simon,

I have updated the "Requirements" section to mention this information: https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-protect-vm-data.html
