### ISSUE TITLE
Clarify "pre-canned policy"

### ISSUE THREAD

**Issue by DrKeno** [NetAppDocs/cloud-manager-backup-restore#94]
Page: [Protect your virtual machines data](https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-protect-vm-data.html)

Clarification is needed for "pre-canned policy". If this is the pre-canned policies in Cloud Backup, then we need to specify Cloud Backup pre-canned policy to distinguish this from SnapCenter for VMware policies.

**Comment by netapp-manishc** [comment]
@DrKeno: These policies are different than SnapCenter Plug-in for VMware vSphere policies. The pre-canned policies in CB for VM are used for easy datastore protection. The pre-canned CB for VM policies can be selected while protecting datastores.

**Comment by DrKeno** [comment]
We should be spelling that out (ie Cloud Backup pre-canned policies) to be clear and distinguish it from the policies mentioned in an earlier bullet item about SCV policies.

Ken

=============================
Ken Jeras • Solution Architect – Virtualization & Converged Infrastructure

NetApp, Inc
Cell: 602-570-7367
***@***.***
netapp.com
________________________________

**Comment by netapp-manishc** [comment]
@DrKeno I have incorporated the change in the topic: https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-protect-vm-data.html
