### ISSUE TITLE
SnapMirror Label needs to be “Yearly” or “yearly” 

### ISSUE THREAD

**Issue by netapp-chandaj** [NetAppDocs/cloud-manager-backup-restore#95]
Page: [Managing cluster-level backup settings](https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-manage-backup-settings-ontap.html)

**Received  feedback via ng-doccomments**

It’s a bit unclear here if the SnapMirror Label needs to be “Yearly” or “yearly” (Snapmirror label is Case sensitive)

Change whether "yearly" snapshots are removed from the source system
When you select the "Yearly" backup label for a backup policy for any of your volumes, the Snapshot copy that is created is very large. By default, these Yearly snapshots are deleted automatically from the source system after being transferred to object storage. You can change this default behavior from the Yearly Snapshot Deletion section.
 
![image](https://user-images.githubusercontent.com/66023260/228765536-d5922914-5b5c-48f5-973f-f1612dce052a.png)

Select Disabled and click Apply if you want to retain the yearly snapshots on the source system.

Also would be great to know How this works as I have a case where the customer has enabled this but the yearly is still existed on the source after the successful transfer

**Comment by netapp-tonacki** [comment]
Hi,  Thanks for your feedback.  I have changed "Yearly" to "yearly" in 2 places.  I am working on some other Backup changes at the moment, so I will publish this update in the next 3 or 4 days and then close the issue.

**Comment by netapp-tonacki** [comment]
The changes are live now, so I'm closing this issue.
